"""update_RawNews_and_Events

Revision ID: 40aa4ffa8d79
Revises: 4b4b82c3e902
Create Date: 2025-12-08 10:33:03.878141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40aa4ffa8d79'
down_revision: Union[str, Sequence[str], None] = '4b4b82c3e902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_raw_news', sa.Column('event_id', sa.Integer(), nullable=True))
    op.alter_column('tg_raw_news', 'importance',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Integer(),
               nullable=False)
    op.create_index(op.f('ix_tg_raw_news_event_id'), 'tg_raw_news', ['event_id'], unique=False)
    op.create_foreign_key(op.f('fk_tg_raw_news_event_id_news_events'), 'tg_raw_news', 'news_events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tg_raw_news_event_id_news_events'), 'tg_raw_news', type_='foreignkey')
    op.drop_index(op.f('ix_tg_raw_news_event_id'), table_name='tg_raw_news')
    op.alter_column('tg_raw_news', 'importance',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.drop_column('tg_raw_news', 'event_id')
    # ### end Alembic commands ###
