"""init

Revision ID: 4b4b82c3e902
Revises: 
Create Date: 2025-12-02 09:42:37.355090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4b82c3e902'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('event_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geo_country', sa.String(length=64), nullable=True),
    sa.Column('geo_region', sa.String(length=64), nullable=True),
    sa.Column('geo_city', sa.String(length=128), nullable=True),
    sa.Column('user_interest_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_events'))
    )
    op.create_index(op.f('ix_news_events_event_ended_at'), 'news_events', ['event_ended_at'], unique=False)
    op.create_index(op.f('ix_news_events_event_started_at'), 'news_events', ['event_started_at'], unique=False)
    op.create_index(op.f('ix_news_events_title'), 'news_events', ['title'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source'))
    )
    op.create_index(op.f('ix_source_description'), 'source', ['description'], unique=False)
    op.create_index(op.f('ix_source_external_id'), 'source', ['external_id'], unique=False)
    op.create_index(op.f('ix_source_name'), 'source', ['name'], unique=False)
    op.create_index(op.f('ix_source_title'), 'source', ['title'], unique=False)
    op.create_index(op.f('ix_source_type'), 'source', ['type'], unique=False)
    op.create_index(op.f('ix_source_url'), 'source', ['url'], unique=False)
    op.create_table('news_event_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['news_events.id'], name=op.f('fk_news_event_tags_event_id_news_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_event_tags')),
    sa.UniqueConstraint('event_id', 'value', name='uq_event_tag')
    )
    op.create_index(op.f('ix_news_event_tags_value'), 'news_event_tags', ['value'], unique=False)
    op.create_table('tg_raw_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('importance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('source_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_fk'], ['source.id'], name=op.f('fk_tg_raw_news_source_fk_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tg_raw_news')),
    sa.UniqueConstraint('source_fk', 'external_id', name='uq_source_msg')
    )
    op.create_index(op.f('ix_tg_raw_news_external_id'), 'tg_raw_news', ['external_id'], unique=False)
    op.create_index(op.f('ix_tg_raw_news_fetched_at'), 'tg_raw_news', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_tg_raw_news_published_at'), 'tg_raw_news', ['published_at'], unique=False)
    op.create_index(op.f('ix_tg_raw_news_source_fk'), 'tg_raw_news', ['source_fk'], unique=False)
    op.create_table('news_event_raw_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('raw_news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['news_events.id'], name=op.f('fk_news_event_raw_links_event_id_news_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_news_id'], ['tg_raw_news.id'], name=op.f('fk_news_event_raw_links_raw_news_id_tg_raw_news'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_event_raw_links')),
    sa.UniqueConstraint('event_id', 'raw_news_id', name='uq_event_raw')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_event_raw_links')
    op.drop_index(op.f('ix_tg_raw_news_source_fk'), table_name='tg_raw_news')
    op.drop_index(op.f('ix_tg_raw_news_published_at'), table_name='tg_raw_news')
    op.drop_index(op.f('ix_tg_raw_news_fetched_at'), table_name='tg_raw_news')
    op.drop_index(op.f('ix_tg_raw_news_external_id'), table_name='tg_raw_news')
    op.drop_table('tg_raw_news')
    op.drop_index(op.f('ix_news_event_tags_value'), table_name='news_event_tags')
    op.drop_table('news_event_tags')
    op.drop_index(op.f('ix_source_url'), table_name='source')
    op.drop_index(op.f('ix_source_type'), table_name='source')
    op.drop_index(op.f('ix_source_title'), table_name='source')
    op.drop_index(op.f('ix_source_name'), table_name='source')
    op.drop_index(op.f('ix_source_external_id'), table_name='source')
    op.drop_index(op.f('ix_source_description'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_news_events_title'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_event_started_at'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_event_ended_at'), table_name='news_events')
    op.drop_table('news_events')
    # ### end Alembic commands ###
